-- AlterTable
ALTER TABLE `admin` MODIFY `role` ENUM('SUPERADMIN', 'KESEKRETARIATAN', 'KEUANGAN', 'ACARA', 'KTA', 'KOMANDAN') NOT NULL DEFAULT 'SUPERADMIN';

-- AlterTable
ALTER TABLE `admin_log` MODIFY `adminRole` ENUM('SUPERADMIN', 'KESEKRETARIATAN', 'KEUANGAN', 'ACARA', 'KTA', 'KOMANDAN') NULL;
