-- AlterTable
ALTER TABLE `tenda_jenis` ADD COLUMN `hargaVendor` INTEGER NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE `transaksi_keuangan` (
    `id` VARCHAR(191) NOT NULL,
    `tanggal` DATE NOT NULL,
    `keterangan` TEXT NOT NULL,
    `jenis` ENUM('PEMASUKAN', 'PENGELUARAN') NOT NULL,
    `kategoriPemasukan` ENUM('PENDAFTARAN', 'SEWA_TENDA', 'SPONSOR', 'PERSENTASE_TENDA') NULL,
    `kategoriPengeluaran` ENUM('SETOR_TENDA', 'OPERASIONAL_DIVISI', 'BEBAN_PENGELUARAN') NULL,
    `debit` INTEGER NOT NULL DEFAULT 0,
    `kredit` INTEGER NOT NULL DEFAULT 0,
    `utang` INTEGER NOT NULL DEFAULT 0,
    `divisi` ENUM('KOMANDAN', 'KETUA_PELAKSANA', 'WAKIL_KETUA', 'BENDAHARA', 'WAKIL_BENDAHARA_1', 'WAKIL_BENDAHARA_2', 'SEKRETARIS', 'WAKIL_SEKRETARIS', 'KESEKRETARIATAN', 'ACARA', 'HUMAS_DAN_DOKUMENTASI', 'GIAT', 'KEAMANAN_DAN_EVAKUASI', 'SANITASI', 'TRANSPORTASI', 'PERKEMAHAN', 'DAPUR_UMUM', 'PERALATAN', 'YANKES') NULL,
    `pic` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
