-- AlterTable
ALTER TABLE `admin` MODIFY `role` ENUM('SUPERADMIN', 'KESEKRETARIATAN', 'KEUANGAN', 'ACARA', 'KTA') NOT NULL DEFAULT 'SUPERADMIN';

-- AlterTable
ALTER TABLE `admin_log` MODIFY `adminRole` ENUM('SUPERADMIN', 'KESEKRETARIATAN', 'KEUANGAN', 'ACARA', 'KTA') NULL;

-- AlterTable
ALTER TABLE `sekolah` ADD COLUMN `sudahCetak` BOOLEAN NOT NULL DEFAULT false;
